#!/usr/bin/env bash

# test/run-all wrapper script

set -euo pipefail

whereami=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

(
    cd "${whereami}/.." && docker run --rm --interactive \
        -v "${PWD}:${PWD}" \
        -v /tmp:/tmp \
        -e "IMAGE=${IMAGE:-}" \
        --workdir "${PWD}" \
        --entrypoint sh \
        "bats/bats:1.13.0" \
        -c "apk add --quiet --no-cache >/dev/null 2>&1 && bats test"
)
