#!/usr/bin/env bash

# Yet another version of `rotate-backups` but this time applied to an AWS S3 backup archive bucket.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

bindir=$(readlink -f "$(dirname "${0}")")
export PATH=${bindir}:${PATH}

# shellcheck disable=SC1091
source /usr/local/include/common-functions

ENV=${ENV:-${HOME:-/root}/.env}
# shellcheck disable=SC1090
[[ -r "${ENV}" ]] && source "${ENV}"

set -o errexit -o errtrace -o nounset -o pipefail
is_true "${DEBUG:=false}" && set -o xtrace -o verbose

function has_cronjob_run() {
    # Check for a success marker file written after each successful rotation.
    # If the cron job is crashing silently, this check will fail and the
    # container will report unhealthy, alerting the operator.
    local marker_file="${HEALTHCHECK_SUCCESS_FILE:-/tmp/.rotate-aws-backups-success}"
    if [[ -f "${marker_file}" ]]; then
        # Check if the marker is recent (within the last 25 hours, allowing for daily cron).
        local marker_age=$(($(date +%s) - $(stat -f %m "${marker_file}" 2>/dev/null || echo 0)))
        [[ ${marker_age} -lt 90000 ]] && return 0
    fi
    error "backup has not run recently"
}

function is_supercronic_running() {
    if pgrep -x supercronic >/dev/null 2>&1; then
        true || info supercronic is running
    else
        error supercronic is not running
    fi
}

function is_crontab_configured() {
    # Read the crontab file directly; supercronic uses a file path, not the
    # OS user crontab managed by crond/crontab(1).
    local _crontab="/var/spool/cron/crontabs/rotate-aws-backups"
    if grep -qF "/usr/local/bin/rotate-aws-backups" "${_crontab}" 2>/dev/null
    then
        true || info crontab is configured
    else
        error crontab is not configured
    fi
}

function is_healthy() {
    is_crontab_configured && is_supercronic_running && has_cronjob_run
}

is_healthy || exit 1

